parameters:



sonata_admin:

    assets:
        stylesheets:
            # Custom assets
            - assets/vendor/bootstrap3-wysihtml5/src/bootstrap-wysihtml5.css
            - assets/vendor/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css

        javascripts:
            # Custom assets
            - assets/vendor/hinclude/hinclude.js
            - assets/vendor/bootstrap3-wysihtml5/lib/js/wysihtml5-0.3.0.js
            - assets/vendor/bootstrap3-wysihtml5/src/bootstrap3-wysihtml5.js
            - assets/vendor/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js

    dashboard:

        blocks:
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [admin, user]

        groups:

            admin:
                label: admin.dashboard.menu.admin.label
                label_catalogue: App
                icon: '<i class="fa fa-list-alt"></i>'
                roles: [ ROLE_ADMIN ]
                items:
                    #- sonata.user.admin.user
                    #- sonata.user.admin.group
                    #- data_dog_audit.admin.audit_log
                    #- app.admin.entity

            user:
                label: admin.dashboard.menu.user.label
                #label_catalogue: App
                icon: '<i class="fa fa-list-alt"></i>'
                roles: [ ROLE_USER ]
                items:
                    #- sonata.user.admin.user
                    #- sonata.user.admin.group
                    #- data_dog_audit.admin.audit_log
                    #- app.admin.entity

services:

# Custom Locale Listener

    application_user.locale_listener:
        class: App\Event\User\Listener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    application_user.user_locale_listener:
        class: App\Event\User\Listener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

# App

    app.admin.post:
        class: App\Admin\PostAdmin
        arguments: [~, App\Entity\Post, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: Post
        public: true

