lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    public_key_path: '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    token_ttl: 86400

gesdinet_jwt_refresh_token:
    ttl: 86400
    #ttl: 2592000
    ttl_update: true
    #firewall: api
    #user_provider: fos_user.user_provider.username_email