fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main

    from_email:
        address:        noreply@example.com
        sender_name:    Symfony App

    # if you change the class configuration, please also alter the sonata_user.yml file
    #user_class:        AppBundle\Entity\Security\User
    user_class:        %security_user_class%

    service:
        user_manager: sonata.user.orm.user_manager

    group:
        #group_class:   AppBundle\Entity\Security\Group
        group_class:   %security_group_class%
        group_manager: sonata.user.orm.group_manager

    registration:
        confirmation:
            enabled:    true
        form:
            #type: application_sonata_user_registration
            type: AppBundle\Form\User\Type\RegistrationFormType
            # if you are using Symfony < 2.8 you should use the type name instead
            # type: app_user_registration

    profile:
        form:
            type: AppBundle\Form\User\Type\ProfileFormType
