fos_rest:
    param_fetcher_listener: true
    body_listener:          true
    format_listener:
        rules:
            - 
              path: '^/api'
              priorities: ['json', 'xml', '*/*', '*']
              fallback_format: json
              prefer_extension: true

            - { path: '^/', stop: true } # Available for version >= 1.5
        
    body_converter:
        enabled: false
        validate: true
    exception:
        messages:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
    view:
        view_response_listener: force
        formats:
            json: true
            xml:  false
            rss:  false
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        mime_types:
            json: ['application/json', 'application/x-json']
        jsonp_handler:
           callback_param: JSON_CALLBACK
    exception:
        enabled: true
    routing_loader:
        default_format: json
        include_format: false        

    disable_csrf_role: ROLE_API