imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

    # Mopa Bootstrap
    - { resource: mopa/mopa_bootstrap.yml }

    # Knp Paginator
    - { resource: knp/knp_paginator.yml }

    # FriendOfSymfony Bundles
    - { resource: fos/fos_rest.yml }
    - { resource: fos/fos_user.yml }
    #- { resource: bazinga/bazinga_hateos.yml }

    # Sonata Core Bundles
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_intl.yml }
    - { resource: sonata/sonata_core.yml }

    # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_user.yml }
    - { resource: sonata/sonata_classification.yml }

    # Assetic
    - { resource: assetic/assetic.yml }

    # Nelmio
    - { resource: nelmio/nelmio_api_doc.yml }
    - { resource: nelmio/nelmio_cors.yml }

    # JMS
    - { resource: jms/jms.yml }

    # Lexik JWT Auth
    - { resource: lexik/lexik_jwt_auth.yml }

    # Gregwar Captcha
    - { resource: gregwar/captcha.yml }

    # Custom overrided options

    - { resource: _custom/custom.yml }


framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
        hinclude_default_template: hinclude.html.twig  
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'

    strict_variables: '%kernel.debug%'

    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'


# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
                # if using pdo_sqlite as your database driver:
                #   1. add the path in parameters.yml
                #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
                #   2. Uncomment database_path in parameters.yml.dist
                #   3. Uncomment next line:
                #path: '%database_path%'

        types:
            json:     Sonata\Doctrine\Types\JsonType
            #currency: Sonata\Component\Currency\CurrencyDoctrineType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'

        #naming_strategy: doctrine.orm.naming_strategy.underscore

        default_entity_manager: default

        entity_managers:
            default:
                auto_mapping: true
                mappings: ~
                naming_strategy: doctrine.orm.naming_strategy.underscore


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool:
        type: memory
        #type: file
        #path: '%kernel.root_dir%/../var/cache/spool'

sensio_framework_extra:
    view:    { annotations: true }
    router:  { annotations: true }
    request: { converters:  true }