imports:
    - { resource: config.yml }
    - { resource: parameters_dev.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar:             true
    #intercept_redirects: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.name%_%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

swiftmailer:
    disable_delivery: false
    delivery_address: dev@symfony.com
    #delivery_whitelist:
    # all email addresses matching this regex will *not* be
    # redirected to dev@example.com
    #    - '/@specialdomain\.com$/'
    # all emails sent to admin@mydomain.com won't
    # be redirected to dev@example.com too
    #    - '/^admin@mydomain\.com$/'    
    spool:
        type: memory
#        #type: file
#        #path: '%kernel.root_dir%/cache/spool'

#sonata_payment:
#    methods:
#        debug: ~
#    services:
#        debug:
#            name:    Debug Payment
#            code:    debug
#            browser: sonata.payment.browser.curl

#            transformers:
#                basket: sonata.payment.transformer.basket
#                order:  sonata.payment.transformer.order

#            options:
#                url_callback:  sonata_payment_callback
#                url_return_ko: sonata_payment_error
#                url_return_ok: sonata_payment_confirmation
