# relative to app/config/routing.yml

# sonata routes
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
#    schemes: [https]

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /user/resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /user/profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /user/register
#    schemes: [https]

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /user/profile

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_redirect_to_index:
    path:   /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

#_redirect_to_admin:
#    path:   /
#    defaults:  
#        _controller: FrameworkBundle:Redirect:redirect
#        route: sonata_admin_dashboard
#        permanent: true
        
homepage:
    path: /home
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    ':home:home.html.twig'              

app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix: /
        
