# relative to app/config/routing.yml

# sonata routes
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
#    schemes: [https]

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /user/resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /user/profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /user/register
#    schemes: [https]

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /user/profile

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"


#sonata_page_ajax_block:
#    path:   /_page/block/{pageId}/{blockId}
#    defaults:  
#        _controller: sonata.page.block.ajax:execute

#sonata_page_exceptions:
#    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
#    prefix: /

#sonata_page_cache:
#    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
#    prefix: /

#sonata_media_gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery

#sonata_media_media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media

#sonata_customer:
#    resource: @SonataCustomerBundle/Resources/config/routing/customer.xml
#    prefix: /shop/user

#sonata_basket:
#    resource: @SonataBasketBundle/Resources/config/routing/basket.xml
#    prefix: /shop/basket

#sonata_order:
#    resource: @SonataOrderBundle/Resources/config/routing/order.xml
#    prefix: /shop/user/order

#sonata_product_catalog:
#    resource: @SonataProductBundle/Resources/config/routing/catalog.xml
#    prefix: /shop/catalog

#sonata_product:
#    resource: @SonataProductBundle/Resources/config/routing/product.xml
#    prefix: /shop/product

#sonata_payment:
#    resource: @SonataPaymentBundle/Resources/config/routing/payment.xml
#    prefix: /shop/payment

#sonata_invoice:
#    resource: @SonataInvoiceBundle/Resources/config/routing/invoice.xml
#    prefix: /shop/user/invoice

#blog:
#    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
#    prefix: /blog

#fos_comment:
#    type: rest
#    resource: "@FOSCommentBundle/Resources/config/routing.yml"
#    prefix: /comments
#    defaults: { _format: html }

# my custom routes

#_imagine:
#    type:     imagine
#    resource: .

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

homepage:
    path:   /
    defaults:  
        _controller: FrameworkBundle:Redirect:redirect
        route: app_index
        #route: sonata_admin_dashboard
        permanent: true
        
#home:
#    path: /home
#    defaults:
#        _controller: FrameworkBundle:Template:template
#        template:    ':home:home.html.twig'              

app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix: /app
        
#_redirect:
#    path:   /redirect
#    defaults:  
#        _controller: FrameworkBundle:Redirect:redirect
#        route: sonata_admin_dashboard
#        #route: homepage
#        permanent: true

