# cross links between kernels
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type:     sonata_admin

sonata_user_admin:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'

#sonata_media_pixlr:
#    resource: '@SonataMediaBundle/Resources/config/routing/pixlr.xml'
#    prefix:   /media

#simple_things_entity_audit:
#    resource: "@SimpleThingsEntityAuditBundle/Resources/config/routing.yml"
#    prefix: /audit/simplethings-entity-audit