doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataClassificationBundle: ~
                    ApplicationSonataClassificationBundle: ~

sonata_classification:
    class:
        tag:            Application\Sonata\ClassificationBundle\Entity\Classification\Tag
        category:       Application\Sonata\ClassificationBundle\Entity\Classification\Category
        context:        Application\Sonata\ClassificationBundle\Entity\Classification\Context
        collection:     Application\Sonata\ClassificationBundle\Entity\Classification\Collection
        media:          Application\Sonata\MediaBundle\Entity\Media\Media

