nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['*']
            #allow_headers: ['X-Custom-Auth']
            allow_headers: ['*']
            allow_methods: ['GET','POST', 'PUT', 'PATCH','DELETE','OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['GET','POST', 'PUT', 'PATCH','DELETE','OPTIONS']
            max_age: 3600
            hosts: ['^api\.']            
