nelmio_api_doc:
    name: System API
    sandbox:
        authentication:
            delivery: http
            #type:     basic
            type:     bearer
        request_format:
            method: accept_header

