assetic:
    debug:          %kernel.debug%
    use_controller: true
    read_from:      %kernel.root_dir%/../web
    write_to:       %kernel.root_dir%/../web
    #bundles:        [] # disable bundles parsing

    filters:
        cssrewrite: ~
        yui_js:  { jar: "%kernel.root_dir%/../bin/yuicompressor.jar" }
        yui_css: { jar: "%kernel.root_dir%/../bin/yuicompressor.jar" }

#    assets:

