# related to app/config/config.yml
imports:
    - { resource: 'services/audit_services.yml'}
    - { resource: 'services/user_services.yml'}

twig:
    globals:
        app_kernel_root_dir: "%kernel.root_dir%"
        app_kernel_web_dir: "%kernel.root_dir%/../web"
        webapp_logo: "%webapp.logo%"
        webapp_short_title: "%webapp.short_title%"
        webapp_title: "%webapp.title%"

fos_user:
    from_email:
        address:        no-reply@symfony.com
        sender_name:    webmaster
    registration:
        confirmation:
            #template:   FOSUserBundle:Registration:email.txt.twig
            from_email:
                address:        no-reply@symfony.com
                sender_name:    webmaster
    resetting:
        email:
            #template:   FOSUserBundle:Resetting:email.txt.twig
            from_email:
                address:        no-reply@symfony.com
                sender_name:    webmaster
        
