services:
#    application_data_dog_audit.example:
#        class: Application\DataDog\AuditBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
            
    datadog.logout.handler.session:
        class: AppBundle\EventHandler\Audit\DataDogSessionLogoutHandler
        public: false
        arguments: ["@security.context","@service_container"]
          
    twig.audit.extension:
        class: AppBundle\Twig\Extension\AuditExtension
        tags:
          - { name: twig.extension }

    data_dog_audit.admin.audit_log:
        class: AppBundle\Admin\Audit\AuditLogAdmin
        arguments: [~, DataDog\AuditBundle\Entity\AuditLog, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: datadog_admin, label: System Logs, label_catalogue: ApplicationDataDogAuditBundle, label_translator_strategy: sonata.admin.label.strategy.underscore}
        calls:
            - [ setTranslationDomain, [AppBundle]]
