services:

    application_user.registration.form.type:
        class: AppBundle\Form\User\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_user_registration }

    # Custom Profile Form Type and Form Handler

    application_user.profile.form.type:
        class: AppBundle\Form\User\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_user_profile }

    # Custom Profile Authentication Form Type

    application_sonata_user.profile.authentication.form.type:
        class: AppBundle\Form\User\Type\ProfileAuthenticationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_user_profile_authentication }

    # Custom Locale Listener

    application_user.locale_listener:
        class: AppBundle\EventListener\User\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    application_user.user_locale_listener:
        class: AppBundle\EventListener\User\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
