services:
#    application_fos_user.example:
#        class: Application\FOS\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

#    application_sonata_user.example:
#        class: Application\Sonata\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # Custom Registration Form Type and Form Handler

    application_user.registration.form.type:
        class: Application\FOS\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_user_registration }

    # Custom Profile Form Type and Form Handler

    application_user.profile.form.type:
        class: Application\FOS\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_user_profile }

    # Custom Profile Authentication Form Type

    application_sonata_user.profile.authentication.form.type:
        class: Application\FOS\UserBundle\Form\Type\ProfileAuthenticationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_user_profile_authentication }

    # Custom Locale Listener

    application_user.locale_listener:
        class: Application\FOS\UserBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    application_user.user_locale_listener:
        class: Application\FOS\UserBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
