services:
#    application_sonata_user.example:
#        class: Application\Sonata\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # Custom Registration Form Type and Form Handler
    
    application_sonata_user.registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_sonata_user_registration }
            
    application_sonata_user.registration.form.handler:
        class: Application\Sonata\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: [@sonata.user.registration.form,@request,@fos_user.user_manager,@fos_user.mailer,@fos_user.util.token_generator]
        scope: request
        public: true

    # Custom Profile Form Type and Form Handler
    
    application_sonata_user.profile.form.type:
        class: Application\Sonata\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_sonata_user_profile }
            
    application_sonata_user.profile.form.handler:
        class: Application\Sonata\UserBundle\Form\Handler\ProfileFormHandler
        arguments: [@sonata.user.profile.form,@request,@fos_user.user_manager]
        scope: request
        public: true

    # Custom Profile Authentication Form Type
    
    application_sonata_user.profile.authentication.form.type:
        class: Application\Sonata\UserBundle\Form\Type\ProfileAuthenticationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_sonata_user_profile_authentication }

    # Custom Locale Listener
    
    application_sonata_user.locale_listener:
        class: Application\Sonata\UserBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber } 
            
    application_sonata_user.user_locale_listener:
        class: Application\Sonata\UserBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }            
